== Creating a custom Eclipse IDE build


=== Building the Eclipse IDE

(((Eclipse IDE build)))
Eclipse uses a Maven based build system for automated builds using the Maven Tycho plug-in. 
Using this build system, you can create your custom build of the Eclipse IDE. 
This approach allows you to add and tests patches based on the latest developments of the Eclipse team.
The results of the build are archive files for the different platforms, which include everything to run an Eclipse IDE.

The build procedure might change over time.
See https://wiki.eclipse.org/Platform-releng/Platform_Build[Platform build wiki] for additional information.

=== Requirements
The build of the Eclipse IDE takes around 2 hours on a Core i5 machine with SSD.
Approximately 25 GB of free space and 4 GB of RAM are required on the hardware-side.
Building of an Eclipse IDE is possible on Windows, OS X and Linux based distributions. 
The following description is based on  Linux.

On the software-side the following software is required:

* Git
* Maven Version 3.3.1
* Oracle 1.8 JDK or higher


=== Build instructions

Perform the following instructions to build the Eclipse IDE.

[source,console]
----
git clone -b master 
   --recursive git://git.eclipse.org/gitroot/platform/eclipse.platform.releng.aggregator.git
mvn clean verify -fae
----

Alternatively, to the aggregated comment for cloning, you can also split the commands:

[source,console]
----
git clone git://git.eclipse.org/gitroot/platform/eclipse.platform.releng.aggregator.git
git submodule init
git checkout master
git pull --recurse-submodules
git submodule update
mvn clean verify -fae
----

At the moment the build process generates "dirt", e.g., it generates files which influence the next build.
To ensure that the repository is reseted to a clean state, you can use the following commands.

[source,console]
----
git submodule foreach git clean -f -d -x
git submodule foreach git reset --hard HEAD
git clean -f -d -x
git reset --hard HEAD
----


[TIP]
====
To skip the tests use `mvn clean verify -DskipTests=true -fae`
====

If you receive `java.lang.OutOfMemoryError` error during the Maven build, you should increase the memory which is available for the build.

[source,console]
----
export MAVEN_OPTS="-Xmx2048m"
----


If the build is successful, the Eclipse SDK is packaged as archive files for all supported platforms. 
These packages can be found in the Git repository in the eclipse.platform.releng.tychoeclipsebuilder/sdk/target/products/* folder:



